project_name: babycron

before:
  hooks:
    - go mod download

builds:
  - id: "linux"
    binary: babycron
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7
    hooks:
      post:
        - upx "{{ .Path }}"
  - id: "windows"
    binary: babycron
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7
  - id: "darwin"
    binary: babycron
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
       - upx "{{ .Path }}"


archives:
  - id: "default"
    builds:
      - babycron
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
  - id: "darwin"
    builds:
      - darwin
    replacements:
      darwin: macOS
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - ids:
    - darwin
    tap:
      owner: meowgorithm
      name: tap
    commit_author:
      name: "Christian Rocha"
      email: "christian@rocha.is"
    homepage: "https://github.com/meowgorithm/babycron"
    description: "Run a single cron job in the foreground."
